name: Build Abseil-cpp for Android (.a)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
        api: [21, 24]  # Можно добавить больше API-уровней

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          add-to-path: true

      - name: Configure CMake for ${{ matrix.abi }}
        run: |
          mkdir build-${{ matrix.abi }}
          cd build-${{ matrix.abi }}
          cmake ../abseil-cpp \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.abi }} \
            -DANDROID_PLATFORM=android-${{ matrix.api }} \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DABSL_BUILD_TESTING=OFF \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON

      - name: Build abseil static libs
        run: |
          cd build-${{ matrix.abi }}
          cmake --build . --config Release

      - name: Upload static library artifacts
        uses: actions/upload-artifact@v4
        with:
          name: abseil-static-${{ matrix.abi }}
          path: build-${{ matrix.abi }}/absl/**/*.a
